/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.sreznick.example.hello;

public class Hello {
    public static String method() {
        return "hello";
    }
}
