/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.sreznick.example.hello;

public class Library {
    public boolean someLibraryMethod() {
        return "world".equals(Hello.method());
    }
}

